### ISSUE TITLE
Update program version through github action

### ISSUE THREAD

**Issue by alegrey91** [alegrey91/fwdctl#21]
This action aims to update the file which contains the version number when a tag is released.
This is an example:
```yaml
name: Upgrade Version
on:
  release:
    types: [published]

jobs:
  upgrade-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pocket-apps/action-update-version@v1
        with:
          files: 'package.json, app.yaml'
          version-regexp: '\d+.\d+.\d+'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
```

More info, here: https://github.com/marketplace/actions/update-files-version-field
