### ISSUE TITLE
proposal: add hooks on rules application/deletion

### ISSUE THREAD

**Issue by alegrey91** [alegrey91/fwdctl#33]
Example:
```yaml
rules:
  - dport: 2022
    saddr: 192.168.122.43
    sport: 22
    iface: eth1
    proto: TCP
    on-create: "/path/to/on-create-script.sh"
    on-delete: "/path/to/on-delete-script.sh"
```
